### ISSUE TITLE
Please add option to change ctrl + k keybind

### ISSUE THREAD

**Issue by anzepintar** [Blagoj5/Tab-Master#11]
Not working on edge, because edge's ctrl + k shortcut for focusing on search bar
Please add option to change this keybind.

P.S. - also not working on github.com, because it opens command palete.

**Comment by Blagoj5** [comment]
@anzepintar, thanks for reporting this, I just want to notify you that there are multiple ways to open Tab-Master:
<img width="633" alt="image" src="https://user-images.githubusercontent.com/50581470/160481580-c8b4b61c-c8b0-45f7-95ea-b999669538d2.png">
1. `Control + Shift + K` will work in all cases (since it's keybinding to the browser)
2. `Control + K` is an event listener which in some cases (like github.com) might cause problems of type 2 commands plates opening Github modal + tab-master modal. Tab-master modal should always be on top like shown in the video (does the same happen to you?): 

https://user-images.githubusercontent.com/50581470/160482440-aeda80ec-2ab3-4bce-8d13-4cbb25806b51.mov

From your request I'll consider adding configurable keybinding at least for toggling (open/close) the modal

### Potential feature
- [ ] Add configurable keybinding for toggle modal

#### NOTE: What to do if tab master does not work on certain pages/browsers?

@anzepintar, I'll say it again I really appreciate your feedback, until I add this feature please use `Control+Shift+K` on the browser. I'll notify you and close this issue as soon as this is added!

**Comment by Blagoj5** [comment]
And for the edge browser problem, I'll fix it on the next release (which will come in few days)

**Comment by Blagoj5** [comment]
@anzepintar, I tested Ctrl + K, CMD + K, Control + Shift + K and CMD + Shift + K on `Microsoft Edge` everything works fine (it's being opened). Can you confirm that this is happening and if so can you tell me what OS you have?

**Comment by anzepintar** [comment]
OS: Windows 10, 21H2
Edge version: 100.0.1185.29
1. click: Ctrl + K -> focus on search bar
2. click: Ctrl + Shift + K -> tab is duplicated
3. click: Ctrl + K -> opens Tab master
4. click: Ctrl + Shift + K -> tab is duplicated
https://user-images.githubusercontent.com/46792251/161601149-907ef6b8-fe83-4f4d-b08f-638f2c7d25a1.mp4

**Comment by anzepintar** [comment]
My issue is the same as #12 but on edge instead of chrome.

**Comment by Blagoj5** [comment]
@anzepintar, yeap the main issue is that most browsers do not allow extensions to run on `new page`. There's a potential solution mentioned in the issue you linked, but you also found another bug on the example page (`example.com`), the Tab-Master modal style is messed up, so I need to fix that!

**Comment by Blagoj5** [comment]
Weird `example.com` style fixed in: 32e8415c517e65e04f8edc4a7593f15452d9d4bd
